name: Docker Publish Knots

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-knots:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed to push to GHCR

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Knots image
      uses: docker/build-push-action@v5
      with:
        context: ./docker/knots
        file: ./docker/knots/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/knots:28.1.knots20250305
        build-args: |
          KNOTS_VERSION=28.1.knots20250305