name: Docker Publish Knots

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-knots:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed to push to GHCR
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/arm/v7]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Knots image
      uses: docker/build-push-action@v5
      with:
        context: ./docker/knots
        file: ./docker/knots/Dockerfile
        push: true
        platforms: ${{ matrix.platform }}
        tags: ghcr.io/${{ github.repository_owner }}/knots:28.1.knots20250305
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          KNOTS_VERSION=28.1.knots20250305

  sign-image:
    needs: build-and-push-knots
    runs-on: ubuntu-latest
    permissions:
      packages: write # Needed to push signature to GHCR
      id-token: write # Needed for keyless signing with Cosign/Sigstore

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3 # Use the latest version

      - name: Sign the multi-arch image
        env:
          COSIGN_EXPERIMENTAL: "true" # Enable keyless signing
        run: |
          cosign sign --yes ghcr.io/${{ github.repository_owner }}/knots:28.1.knots20250305